- .azure-pipelines/azure-pipelines-linux.yml
- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/migrations/icu70.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- .github/CODEOWNERS
- .travis.yml
- README.md
- conda-forge.yml
- recipe/meta.yaml
- recipe/patches/0030-include_uitility_mbgl_unique_any.patch
Closes #21
Closes #19
Checklist
> 5.15.3 with migrations

- .ci_support/migrations/gstreamer120.yaml
- recipe/build.sh
- recipe/meta.yaml
Checklist
Fix #25 
Fix based on https://gitlab.kitware.com/utils/ci-utilities/-/merge_requests/10
> Make tools, fix #25

- recipe/meta.yaml
> update to 5.15.4

- recipe/bld.bat
- recipe/build.sh
- recipe/meta.yaml
Also available in qt-main, needed for qt6-webengine
> 6.x: Enable webchannel, websockets

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/migrations/alsa_lib128.yaml
- .ci_support/migrations/gstreamer121.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- recipe/meta.yaml
> Alsa migration 1.28 qt6

- .ci_support/linux_64_openssl1.1.1.yaml
- .ci_support/linux_64_openssl3.yaml
- .ci_support/linux_aarch64_openssl1.1.1.yaml
- .ci_support/linux_aarch64_openssl3.yaml
- .ci_support/osx_64_openssl1.1.1.yaml
- .ci_support/osx_64_openssl3.yaml
- .ci_support/osx_arm64_openssl1.1.1.yaml
- .ci_support/osx_arm64_openssl3.yaml
- .ci_support/win_64_openssl1.1.1.yaml
- .ci_support/win_64_openssl3.yaml
- recipe/meta.yaml
Review and merge https://github.com/conda-forge/qt-main-feedstock/pull/74 first
Checklist
> Qt6 libsqlite

- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_openssl1.1.1.yaml
- .ci_support/linux_64_openssl3.yaml
- .ci_support/linux_aarch64_openssl1.1.1.yaml
- .ci_support/linux_aarch64_openssl3.yaml
- .ci_support/osx_64_openssl1.1.1.yaml
- .ci_support/osx_64_openssl3.yaml
- .ci_support/osx_arm64_openssl1.1.1.yaml
- .ci_support/osx_arm64_openssl3.yaml
- .ci_support/win_64_openssl1.1.1.yaml
- .ci_support/win_64_openssl3.yaml
- recipe/bld.bat
- recipe/build.sh
- recipe/meta.yaml
> qt6: Drop charts, datavis

- .ci_support/linux_64_openssl1.1.1.yaml
- .ci_support/linux_64_openssl3.yaml
- .ci_support/linux_aarch64_openssl1.1.1.yaml
- .ci_support/linux_aarch64_openssl3.yaml
- .ci_support/migrations/krb5120.yaml
- .ci_support/osx_64_openssl1.1.1.yaml
- .ci_support/osx_64_openssl3.yaml
- .ci_support/osx_arm64_openssl1.1.1.yaml
- .ci_support/osx_arm64_openssl3.yaml
- .ci_support/win_64_openssl1.1.1.yaml
- .ci_support/win_64_openssl3.yaml
- recipe/meta.yaml
> qt6 - pin lib clang between build and host

- .ci_support/linux_64_openssl1.1.1.yaml
- .ci_support/linux_64_openssl3.yaml
- .ci_support/linux_aarch64_openssl1.1.1.yaml
- .ci_support/linux_aarch64_openssl3.yaml
- .ci_support/migrations/krb5120.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_openssl1.1.1.yaml
- .ci_support/win_64_openssl3.yaml
- recipe/meta.yaml
> qt5 Pin libclang for osx for enhanced compatibility

- .ci_support/linux_64_openssl1.1.1.yaml
- .ci_support/linux_64_openssl3.yaml
- .ci_support/linux_aarch64_openssl1.1.1.yaml
- .ci_support/linux_aarch64_openssl3.yaml
- .ci_support/migrations/libtiff45.yaml
- .ci_support/osx_64_openssl1.1.1.yaml
- .ci_support/osx_64_openssl3.yaml
- .ci_support/osx_arm64_openssl1.1.1.yaml
- .ci_support/osx_arm64_openssl3.yaml
- .ci_support/win_64_openssl1.1.1.yaml
- .ci_support/win_64_openssl3.yaml
- recipe/meta.yaml
> Qt6 libtiff 4.5

- recipe/meta.yaml
> update recipe maintainer with linux_ppc64le manual build

- .azure-pipelines/azure-pipelines-win.yml
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- README.md
- recipe/bld.bat
- recipe/build.sh
- recipe/meta.yaml
- recipe/run_test.bat
- recipe/run_test.sh
> Add `qt6.conf` file

- conda-forge.yml
> Pin vs2019

- recipe/bld.bat
- recipe/meta.yaml
> qt6: Try copy instead mklink

- recipe/bld.bat
- recipe/meta.yaml
- recipe/run_test.bat
as discussed in #126
Checklist
> Fix qt6.conf generation on windows

- recipe/conda_build_config.yaml
> 6.x: Drop vs2019 pin

- recipe/bld.bat
- recipe/build.sh
- recipe/meta.yaml
> 6.x: Enable designer

- recipe/build.sh
- recipe/meta.yaml
> 6.x: Pin clang<16

- recipe/meta.yaml
> Rebuild Qt 5.15.8 with clang 15 specified

- recipe/meta.yaml
> try Mirror

- .ci_support/osx_arm64_.yaml
- recipe/conda_build_config.yaml
- recipe/meta.yaml
> Pin clang 15

- .ci_support/osx_64_.yaml
- recipe/conda_build_config.yaml
- recipe/meta.yaml
> Update to 6.6.0

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- .scripts/run_win_build.bat
- recipe/meta.yaml
> Pin openssl<3.2

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- recipe/meta.yaml
> Unpin openssl

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/migrations/libxml2212.yaml
- recipe/meta.yaml
> Qt6 libxml2212

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/migrations/libxml2212.yaml
- .scripts/build_steps.sh
- .scripts/run_docker_build.sh
- .scripts/run_osx_build.sh
- .scripts/run_win_build.bat
- .travis.yml
- README.md
- recipe/meta.yaml
> qt5: Libxml2212

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/migrations/libtiff46.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- .gitignore
- recipe/meta.yaml
- recipe/patches/0001-CMake-Fix-user_facing_tool_links.txt-for-Apple-platf.patch
> Fix for QTBUG-120487

- recipe/bld.bat
- recipe/meta.yaml
see also https://bugreports.qt.io/browse/QTBUG-120515
cc @hmaarrfk
> Fix qmake paths

- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- recipe/meta.yaml
> Rerender qt6

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/migrations/pcre21043.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- .scripts/run_win_build.bat
- build-locally.py
- recipe/meta.yaml
> Add qt6 pcre2 migration for 10.43

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/migrations/libxml2212.yaml
- .ci_support/migrations/mysql_devel83.yaml
- .ci_support/migrations/pulseaudio17.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- .scripts/run_win_build.bat
- azure-pipelines.yml
- conda-forge.yml
- recipe/meta.yaml
xref: https://github.com/conda-forge/qt-main-feedstock/issues/240
closes #243
closes https://github.com/conda-forge/qt-main-feedstock/pull/248
Checklist
> Unpin upper bound of libclang for qt6 + mysql 8.3 + pulseaudio 17

- .azure-pipelines/azure-pipelines-osx.yml
- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/migrations/pcre21043.yaml
- .ci_support/win_64_.yaml
- recipe/conda_build_config.yaml
- recipe/meta.yaml
> stdlib('c') migration

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- recipe/meta.yaml
> Update to 6.7.3

- recipe/meta.yaml
> Re-enable cross builds

- .gitignore
- recipe/meta.yaml
> Update to 6.8.3

- recipe/build.sh
- recipe/test/CMakeLists.txt
> Fix arm64 build

- recipe/build.sh
> no_adhoc_codesign

- .ci_support/migrations/harfbuzz11.yaml
- .ci_support/win_64_.yaml
- .scripts/run_docker_build.sh
- build-locally.py
- recipe/bld.bat
- recipe/conda_build_config.yaml
- recipe/meta.yaml
> Update to 6.9.0
